import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class StudentLogForm extends javax.swing.JFrame {

    /**
     * Creates new form StudentLogForm
     */
    public StudentLogForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtStudTC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnStudEnter = new javax.swing.JButton();
        pswStudPass = new javax.swing.JPasswordField();
        lblStudWarning = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("T.C NUM:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 70, 61, 43);
        getContentPane().add(txtStudTC);
        txtStudTC.setBounds(190, 70, 139, 43);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 130, 90, 43);

        btnStudEnter.setIcon(new javax.swing.ImageIcon("C:\\Users\\MeteK\\Desktop\\Lessons\\Java Programming\\SchoolManagementSystem\\User-Interface-Login-icon.png")); // NOI18N
        btnStudEnter.setText("ENTER");
        btnStudEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudEnterActionPerformed(evt);
            }
        });
        getContentPane().add(btnStudEnter);
        btnStudEnter.setBounds(190, 200, 140, 73);
        getContentPane().add(pswStudPass);
        pswStudPass.setBounds(190, 130, 139, 43);

        lblStudWarning.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblStudWarning.setForeground(new java.awt.Color(255, 0, 0));
        lblStudWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblStudWarning);
        lblStudWarning.setBounds(30, 280, 469, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\MeteK\\Desktop\\Lessons\\Java Programming\\SchoolManagementSystem\\81581ee6828d3be.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 650, 410);

        setSize(new java.awt.Dimension(670, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStudEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudEnterActionPerformed
        String host ="jdbc:derby://localhost:1527/SchoolDataBase";
        String userName="school";
        String userPass="123456";
        String dept="";
        
        try{
            String pw=new String(pswStudPass.getPassword());
            boolean enter=false;
            Connection con=DriverManager.getConnection(host, userName,userPass);
            String sql="SELECT * FROM STUDENTINFO WHERE TCNUM = '" + txtStudTC.getText() +"'";
            /*Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery(sql);*/
            PreparedStatement stmt=con.prepareStatement(sql);
            ResultSet rs=stmt.executeQuery();
            
            while (rs.next()) {
                String pass = rs.getString("PASSWORD");
                dept=rs.getString("DEPARTMENT");

                if (pass == null ? pw == null : pass.equals(pw)) { //PLEASE IMPROVE HERE IF NECESSARY TO PUT BREAK OR NOT!!
                    enter=true;
                }
            }
            String tc=txtStudTC.getText();
            if(enter==true){
                this.setVisible(false);
                StudentForm studentFrame=new StudentForm(tc,dept);
                studentFrame.setVisible(true);
            }
            
            else
            {
                lblStudWarning.setText("You've entered something uncorrect!");
            }
 
        } 
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(null, e);
        }        

    }//GEN-LAST:event_btnStudEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudEnter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblStudWarning;
    private javax.swing.JPasswordField pswStudPass;
    private javax.swing.JTextField txtStudTC;
    // End of variables declaration//GEN-END:variables
}
